### ISSUE TITLE
No Json Response format

### ISSUE THREAD

**Issue by GrazingScientist** [search5/solrpy3#1]
As far as I could test it, there is no support for a JSON response format. However, the standard response format in Solr is Json (as of Solr 7.2). Furthermore, the parameter "wt=xml" to force Solr to use the XML format is ignored. At least, the latter should be resolved.

**Comment by search5** [comment]
We have updated the solrpy library that solved your problem with the answer you provided. The new update forced the response document to be requested in XML and was modified to work with both Python 2 and 3.

And finally, this issue should be solrpy3 project terminated from my project and downloaded from the original project (pypi.org/project/solrpy).

thank you for telling me.
